author: eccentric_nz
description: Allows you to store your XP by clicking on a special sign
main: me.eccentric_nz.plugins.xpkeeper.Xpkeeper
dev-url: http://de.bukkit.org/server-mods/xpkeeper/
name: XPKeeper
startup: postworld
version: '1.0.2'
permissions:
  xpkeeper.use:
    description: Allow players to use XPKeeper signs
    default: true
commands:
  giveXP:
    description: Give yourself XP.
    usage: /<command> [amount]
  setXP:
    description: Set your total XP.
    usage: /<command> [amount]
  xpkremove:
    description: Remove an XPKeeper sign.
    usage: /<command>
  xpkfist:
    description: Toggle the XPKeeper must_use_fist config option.
    usage: /<command>
