author: eccentric_nz
description: Allows you to store your XP by clicking on a special sign
main: me.eccentric_nz.plugins.xpkeeper.Xpkeeper
dev-url: http://de.bukkit.org/server-mods/xpkeeper/
name: XPKeeper
startup: postworld
version: '1.0.2'
permissions:
  xpkeeper.use:
    description: Allow players to use XPKeeper signs
    default: true
commands:
  setXP:
    description: Set your Total EP.
    usage: /<command> [amount]
  xpkremove:
    description: Remove an XPKeeper sign.
    usage: /<command>
